### ISSUE TITLE
SDF from PDB not PDBBind?

### ISSUE THREAD

**Issue by gieses** [RMeli/PDBbind-docking#1]
Thanks for putting up the repo!

I'd be happy if you could explain why you choose to get the ligands from the PDB (https://github.com/RMeli/PDBbind-docking/blob/master/01_clean.sh) and not use the ones from the PDBBind itself? 
Thanks!
Cheers,
Sven

**Comment by RMeli** [comment]
Hi @gieses . IIRC, RDKit was complaining with multiple molecules from the PDBbind and therefore I downloaded the original files from the PDB, which seemed to be better.

Please note that the goal of this pipeline was to generated multiple docking poses to test the correctness of [sPyRMSD](https://github.com/RMeli/spyrmsd) and therefore docking was performed with the default parameters, I did not put any effort in correcting problems or preparing the systems, and the results were not assessed in any way (I will make this clear on the README).

**Comment by RMeli** [comment]
Clarified in the README that docking was not properly assessed (02df4a8).
